"""
PDF report generation for a completed inspection.

Design goals:
- The PDF is a rendering of already-computed, persisted facts/findings. It
  does not perform any new legal evaluation.
- A clear disclaimer is always printed, matching the platform's legal
  posture: automated screening / pre-inspection aid, not a final legal
  determination.
- No external HTML/browser dependency (WeasyPrint has heavy native deps that
  are awkward in constrained/offline build environments); reportlab is pure
  Python and reliable to install.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

DISCLAIMER = (
    "This report is generated by an automated screening / pre-inspection aid "
    "under the Legal Metrology (Packaged Commodities) Rules, 2011. It is NOT "
    "a final legal determination. Findings marked UNCERTAIN or REVIEW "
    "REQUIRED must be resolved by an authorized Legal Metrology inspector "
    "before any enforcement action is taken."
)

STATUS_COLORS = {
    "PASS": colors.HexColor("#1a7f37"),
    "FAIL": colors.HexColor("#cf222e"),
    "UNCERTAIN": colors.HexColor("#9a6700"),
    "EXEMPT": colors.HexColor("#6639ba"),
}


def _status_of(obj: Any) -> str:
    value = _get(obj, "status")
    if hasattr(value, "value"):
        value = value.value
    return str(value or "UNCERTAIN").upper()


def _get(obj: Any, key: str, default: Any = None) -> Any:
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def build_inspection_report_pdf(inspection: Dict[str, Any]) -> bytes:
    """
    Render one inspection (as returned by db.get_inspection_detail /
    ProductInspection.model_dump()) into a PDF report and return the raw
    bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=16, spaceAfter=4,
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=10, spaceAfter=4)
    normal = styles["Normal"]
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#7a0000"), borderColor=colors.HexColor("#7a0000"),
        borderWidth=0.5, borderPadding=6, backColor=colors.HexColor("#fff5f5"),
    )

    story: list[Any] = []

    inspection_id = _get(inspection, "inspection_id", "unknown")
    story.append(Paragraph("Legal Metrology Compliance Inspection Report", title_style))
    story.append(Paragraph(f"Inspection ID: {inspection_id}", normal))
    story.append(Spacer(1, 4))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    story.append(Spacer(1, 10))

    # --- Summary table ---------------------------------------------------
    overall_status = _get(inspection, "overall_status", "UNCERTAIN")
    if hasattr(overall_status, "value"):
        overall_status = overall_status.value

    summary_rows = [
        ["Field", "Value"],
        ["Product / Product ID", str(_get(inspection, "product_id", "-"))],
        ["Product category", str(_get(inspection, "product_category", "-"))],
        ["Sale type", str(_get(inspection, "sale_type", "-"))],
        [
            "Net quantity",
            f"{_get(inspection, 'net_quantity_value', _get(inspection, 'package_weight_or_volume', '-'))} "
            f"{_get(inspection, 'net_quantity_unit', _get(inspection, 'package_weight_unit', ''))}",
        ],
        ["MRP", str(_get(inspection, "mrp", "not observed"))],
        ["Overall status", str(overall_status).upper()],
        ["Review required", str(_get(inspection, "review_required", False))],
        [
            "Generated",
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        ],
    ]
    exempt_reason = _get(inspection, "exempt_reason")
    if exempt_reason:
        summary_rows.append(["Exemption reason", str(exempt_reason)])

    summary_table = Table(summary_rows, colWidths=[55 * mm, 110 * mm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # --- Findings ----------------------------------------------------------
    story.append(Paragraph("Rule Findings", h2))
    findings = _get(inspection, "findings", []) or []
    facts = _get(inspection, "facts", []) or []

    rows_source = findings if findings else facts
    if not rows_source:
        story.append(Paragraph("No rule findings were recorded for this inspection.", normal))
    else:
        table_rows = [["Rule / Field", "Status", "Reason", "Confidence"]]
        for item in rows_source:
            label = _get(item, "rule_id") or _get(item, "field") or "-"
            status = _status_of(item)
            reason = str(_get(item, "reason", "") or "")[:220]
            confidence = _get(item, "confidence", None)
            confidence_str = f"{float(confidence):.2f}" if confidence is not None else "-"
            table_rows.append([
                Paragraph(str(label), small),
                status,
                Paragraph(reason, small),
                confidence_str,
            ])

        findings_table = Table(
            table_rows, colWidths=[35 * mm, 22 * mm, 88 * mm, 20 * mm], repeatRows=1
        )
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_index, item in enumerate(rows_source, start=1):
            status = _status_of(item)
            color = STATUS_COLORS.get(status, colors.black)
            style_commands.append(("TEXTCOLOR", (1, row_index), (1, row_index), color))
            style_commands.append(("FONTNAME", (1, row_index), (1, row_index), "Helvetica-Bold"))
        findings_table.setStyle(TableStyle(style_commands))
        story.append(findings_table)

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "Every finding above is traceable to a versioned rule identifier, the "
        "underlying extracted evidence, and a confidence score. Findings with "
        "status UNCERTAIN reflect insufficient evidence, not a legal "
        "determination of non-compliance.",
        small,
    ))

    doc.build(story)
    return buffer.getvalue()
