"""
PDF report generation for a completed inspection.

Design goals:
- The PDF is a rendering of already-computed, persisted facts/findings. It
  does not perform any new legal evaluation.
- The document may not assert more than it can show. It prints the rule version
  applied and the source image plus region for each finding, and where those are
  absent it says so rather than leaving the reader to assume traceability. If
  extracted facts are standing in for absent findings, that substitution is
  disclosed instead of being presented as a rule finding.
- A clear disclaimer is always printed, matching the platform's legal
  posture: automated screening / pre-inspection aid, not a final legal
  determination.
- No external HTML/browser dependency (WeasyPrint has heavy native deps that
  are awkward in constrained/offline build environments); reportlab is pure
  Python and reliable to install.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from schema import UNATTRIBUTED_IMAGE_ID

DISCLAIMER = (
    "This report is generated by an automated screening / pre-inspection aid "
    "under the Legal Metrology (Packaged Commodities) Rules, 2011. It is NOT "
    "a final legal determination. Findings marked UNCERTAIN or REVIEW "
    "REQUIRED must be resolved by an authorized Legal Metrology inspector "
    "before any enforcement action is taken."
)

STATUS_COLORS = {
    "PASS": colors.HexColor("#1a7f37"),
    "FAIL": colors.HexColor("#cf222e"),
    "UNCERTAIN": colors.HexColor("#9a6700"),
    "EXEMPT": colors.HexColor("#6639ba"),
}


#: Printed in the Evidence column when a finding names no source image at all.
#: Kept distinct from the UNATTRIBUTED sentinel: "no evidence was recorded" and
#: "evidence was recorded but its source image is unknown" are different facts
#: about the inspection, and collapsing them would hide a provenance break.
_NO_EVIDENCE = "no evidence recorded"


def _status_of(obj: Any) -> str:
    value = _get(obj, "status")
    if hasattr(value, "value"):
        value = value.value
    return str(value or "UNCERTAIN").upper()


def _get(obj: Any, key: str, default: Any = None) -> Any:
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _bbox_text(bbox: Any) -> Optional[str]:
    """
    Render a region as integer pixel coordinates in the ORIGINAL image.

    Coordinates are printed rather than summarised because the point of the
    region is that a reviewer can go back to the stored original and look at
    exactly those pixels. A rounded or relative figure would not let them.
    """
    if bbox is None:
        return None

    if isinstance(bbox, (list, tuple)) and len(bbox) == 4:
        try:
            x, y, w, h = (float(v) for v in bbox)
        except (TypeError, ValueError):
            return None
    else:
        x = _get(bbox, "x")
        y = _get(bbox, "y")
        w = _get(bbox, "width")
        h = _get(bbox, "height")
        if None in (x, y, w, h):
            return None
        try:
            x, y, w, h = float(x), float(y), float(w), float(h)
        except (TypeError, ValueError):
            return None

    return f"({x:.0f},{y:.0f}) {w:.0f}x{h:.0f}px"


def _evidence_cell(item: Any) -> str:
    """
    Describe, for one finding, what a reviewer would have to look at.

    WHY THIS IS PRINTED AT ALL. The report already asserted that every finding
    is "traceable to ... the underlying extracted evidence", but rendered only
    the rule id, status, reason and confidence — so the document made a
    traceability claim that nothing in the document supported, and a finding
    resting on no evidence looked identical to one resting on a located region.
    Invariant 17 requires a finding to be traceable to its evidence and rule
    version; a report is where that traceability is actually exercised.

    Works on both an in-memory EvidenceReference and the plain dict that comes
    back out of `evidence_json` after reload, because the report is rendered
    from persisted rows in the live path and from model objects in tests.
    """
    refs = _get(item, "evidence", None) or []
    if not refs:
        return _NO_EVIDENCE

    parts = []
    for ref in refs:
        image_id = _get(ref, "image_id") or None
        region = _bbox_text(_get(ref, "bbox"))

        if image_id == UNATTRIBUTED_IMAGE_ID:
            # Stays conspicuous on the page. A reader must be able to see that
            # the chain back to a photograph is broken for this finding.
            label = "SOURCE IMAGE NOT RECORDED"
            parts.append(f"{label} — region {region}" if region else label)
            continue

        if image_id and region:
            parts.append(f"{image_id} @ {region}")
        elif image_id:
            parts.append(f"{image_id} — region not recorded")
        elif region:
            parts.append(f"region {region} — source image not recorded")

    return "<br/>".join(parts) if parts else _NO_EVIDENCE


def _is_locatable(item: Any) -> bool:
    """
    Could a reviewer actually be shown this finding's evidence?

    Mirrors `schema.EvidenceReference.is_locatable()`: it takes BOTH a named
    source image and a region within it. A region with no source image is not a
    weaker form of traceability, it is none — nobody can act on
    "(115,700) 420x52px" without knowing which photograph it indexes into. This
    is applied to the whole finding, so a finding is locatable when at least one
    of its references is.

    Works on a dict reloaded from `evidence_json` as well as on the model object,
    which is why it does not simply call the schema method.
    """
    for ref in _get(item, "evidence", None) or []:
        image_id = _get(ref, "image_id")
        if not image_id or image_id == UNATTRIBUTED_IMAGE_ID:
            continue
        if _bbox_text(_get(ref, "bbox")) is not None:
            return True
    return False


def _missing_evidence_text(item: Any) -> str:
    """
    "Nothing was observed" and "something was observed and contradicts the
    declaration" are different legal positions, so the report must not leave the
    reader to infer which one produced an UNCERTAIN or FAIL.
    """
    missing = _get(item, "missing_evidence", None) or []
    if not missing:
        return ""
    names = ", ".join(str(m) for m in missing)
    return f"Evidence not observed for: {names}."


def build_findings_section(inspection: Any) -> Dict[str, Any]:
    """
    Decide WHAT the findings section of the report says, separately from how it
    is drawn.

    WHY THIS IS A SEPARATE FUNCTION. The choices made here are the legally
    significant ones: whether the rows being shown are findings or merely
    extracted facts, whether the document is entitled to claim traceability, and
    whether a provenance break is disclosed. While that logic lived inline in
    `build_inspection_report_pdf`, the only way to test it was to render a PDF
    and parse it back, which needs a PDF text extractor that is not available
    here — so the report's claims about its own evidence were untestable. Pulling
    them into a pure function makes the assertions directly checkable.

    Returns a dict with:
      heading        - section title
      warning        - conspicuous notice, or None
      rows           - list of dicts, one per row, already flattened for display
      closing        - the statement printed under the table
      showing_facts  - True when facts are standing in for absent findings
    """
    findings = _get(inspection, "findings", []) or []
    facts = _get(inspection, "facts", []) or []

    # WHY THIS IS NO LONGER A SILENT FALLBACK.
    # This was `rows_source = findings if findings else facts`, printed under a
    # "Rule Findings" heading with a closing sentence asserting that every row
    # was traceable to a versioned rule identifier. Findings were not persisted
    # at all, so in the live path the branch always taken was the fallback:
    # every report ever generated rendered extracted FACTS while claiming they
    # were rule findings. The document looked plausible, which is precisely why
    # the missing table went unnoticed. Facts are observations; findings are
    # legal conclusions about requirements. Substituting one for the other
    # without saying so is a misrepresentation in a document intended to support
    # an inspection.
    showing_facts = not findings
    rows_source = findings if findings else facts

    heading = (
        "Extracted Facts (no rule findings available)"
        if showing_facts
        else "Rule Findings"
    )

    warning: Optional[str] = None
    if _get(inspection, "findings_unavailable"):
        warning = (
            "WARNING: the stored rule findings for this inspection could not be "
            "read back from the database. The rows below are extracted "
            "observations, not legal findings, and this report must not be "
            "relied upon as a record of the evaluation."
        )
    elif showing_facts and rows_source:
        warning = (
            "No rule findings were recorded for this inspection, so the rows "
            "below are the underlying extracted observations. They are NOT rule "
            "findings: no requirement was evaluated against them here and no "
            "rule version applies to them."
        )

    rows = []
    for item in rows_source:
        reason = str(_get(item, "reason", "") or "")[:220]
        not_observed = _missing_evidence_text(item)
        if not_observed:
            reason = f"{reason} {not_observed}".strip()

        confidence = _get(item, "confidence", None)
        try:
            confidence_str = f"{float(confidence):.2f}" if confidence is not None else "-"
        except (TypeError, ValueError):
            confidence_str = "-"

        rows.append({
            "label": str(_get(item, "rule_id") or _get(item, "field") or "-"),
            # A fact has no rule version by definition. "-" keeps the absence
            # visible instead of letting the column look complete.
            "rule_version": str(_get(item, "rule_version") or "-"),
            "status": _status_of(item),
            "reason": reason,
            "evidence": _evidence_cell(item),
            "locatable": _is_locatable(item),
            "confidence": confidence_str,
        })

    # The closing statement is derived from what was actually rendered. The
    # previous fixed text asserted full traceability unconditionally, including
    # in the cases where rows carried no evidence region or no rule version.
    if not rows:
        closing = (
            "No rule findings and no extracted facts were recorded for this "
            "inspection. Nothing in this report should be read as a compliance "
            "determination."
        )
    elif showing_facts:
        closing = (
            "The rows above are extracted observations, not legal findings. No "
            "rule version applies to them and they do not constitute a "
            "compliance determination."
        )
    else:
        closing = (
            "Each finding above names the rule version applied and, where "
            "evidence was observed, the source image and the region within it "
            "in original-image pixel coordinates. Findings with status "
            "UNCERTAIN reflect insufficient evidence, not a legal determination "
            "of non-compliance."
        )
        untraceable = sum(1 for row in rows if not row["locatable"])
        if untraceable:
            # Counts findings with no evidence AND findings whose region names no
            # source image. Both are equally unshowable to a reviewer, and an
            # earlier version of this count included only the first, which
            # understated the gap in exactly the case where provenance had broken.
            closing += (
                f" {untraceable} of {len(rows)} findings cannot be shown to a "
                "reviewer in context: they carry no recorded evidence region, "
                "or no source image to locate that region in."
            )

    return {
        "heading": heading,
        "warning": warning,
        "rows": rows,
        "closing": closing,
        "showing_facts": showing_facts,
    }


def build_inspection_report_pdf(
    inspection: Dict[str, Any],
    *,
    rag_grounding: Optional[Sequence[Any]] = None,
) -> bytes:
    """
    Render one inspection (as returned by db.get_inspection_detail /
    ProductInspection.model_dump()) into a PDF report and return the raw
    bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=16, spaceAfter=4,
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=10, spaceAfter=4)
    normal = styles["Normal"]
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#7a0000"), borderColor=colors.HexColor("#7a0000"),
        borderWidth=0.5, borderPadding=6, backColor=colors.HexColor("#fff5f5"),
    )

    story: list[Any] = []

    inspection_id = _get(inspection, "inspection_id", "unknown")
    story.append(Paragraph("Legal Metrology Compliance Inspection Report", title_style))
    story.append(Paragraph(f"Inspection ID: {inspection_id}", normal))
    story.append(Spacer(1, 4))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    story.append(Spacer(1, 10))

    # --- Summary table ---------------------------------------------------
    overall_status = _get(inspection, "overall_status", "UNCERTAIN")
    if hasattr(overall_status, "value"):
        overall_status = overall_status.value

    summary_rows = [
        ["Field", "Value"],
        ["Product / Product ID", str(_get(inspection, "product_id", "-"))],
        ["Product category", str(_get(inspection, "product_category", "-"))],
        ["Sale type", str(_get(inspection, "sale_type", "-"))],
        [
            "Net quantity",
            f"{_get(inspection, 'net_quantity_value', _get(inspection, 'package_weight_or_volume', '-'))} "
            f"{_get(inspection, 'net_quantity_unit', _get(inspection, 'package_weight_unit', ''))}",
        ],
        ["MRP", str(_get(inspection, "mrp", "not observed"))],
        ["Overall status", str(overall_status).upper()],
        ["Review required", str(_get(inspection, "review_required", False))],
        [
            "Generated",
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        ],
    ]
    exempt_reason = _get(inspection, "exempt_reason")
    if exempt_reason:
        summary_rows.append(["Exemption reason", str(exempt_reason)])

    decl_summary = _get(inspection, "declaration_summary") or {}
    decls = _get(inspection, "declarations") or []
    if not decl_summary and decls:
        v_count = sum(
            1 for d in decls
            if str(_get(d, "status")).upper() == "VERIFIED"
            or getattr(_get(d, "status"), "value", "") == "VERIFIED"
        )
        app_count = sum(
            1 for d in decls
            if str(_get(d, "status")).upper() not in ("NOT_APPLICABLE", "NOT APPLICABLE")
            and getattr(_get(d, "status"), "value", "") != "NOT_APPLICABLE"
        )
        decl_summary = {"verified": v_count, "applicable": app_count}

    if decl_summary and "applicable" in decl_summary:
        v_count = decl_summary.get("verified", 0)
        app_count = decl_summary.get("applicable", 0)
        pct = (v_count / app_count * 100) if app_count > 0 else 0
        summary_rows.append(["Declarations verified", f"{v_count} of {app_count} applicable declarations verified ({pct:.0f}%)"])

    summary_table = Table(summary_rows, colWidths=[55 * mm, 110 * mm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # --- Canonical Declarations Table --------------------------------------
    if decls:
        story.append(Paragraph("Canonical Mandatory Declarations Matrix", h2))
        story.append(Paragraph(
            "Evaluation of mandatory packaged commodity declarations under Rule 6 of the Legal Metrology "
            "(Packaged Commodities) Rules, 2011. Denominator includes only applicable declarations for this product category.",
            disclaimer_style,
        ))
        story.append(Spacer(1, 6))

        decl_header_style = ParagraphStyle(
            "DeclTableHeader", parent=small, fontName="Helvetica-Bold",
            textColor=colors.black, leading=9,
        )
        decl_table_rows = [[
            Paragraph(t, decl_header_style)
            for t in ("Declaration Field", "Extracted Value", "Status", "Clause / Rule", "Verification Reason")
        ]]
        decl_style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        DECL_STATUS_COLORS = {
            "VERIFIED": colors.HexColor("#1a7f37"),
            "REVIEW_REQUIRED": colors.HexColor("#9a6700"),
            "PARTIALLY_DETECTED": colors.HexColor("#9a6700"),
            "NON_COMPLIANT": colors.HexColor("#cf222e"),
            "NOT_APPLICABLE": colors.HexColor("#57606a"),
            "NOT_DETECTED_IN_PROVIDED_IMAGES": colors.HexColor("#cf222e"),
        }
        for row_idx, d in enumerate(decls, start=1):
            c_name = _get(d, "canonical_name") or _get(d, "field") or "-"
            c_val = str(_get(d, "value") or _get(d, "normalized_value") or "Not detected")
            if len(c_val) > 40:
                c_val = c_val[:37] + "..."
            d_status = _get(d, "status")
            if hasattr(d_status, "value"):
                d_status = d_status.value
            d_status = str(d_status or "UNCERTAIN").upper()
            rule_ref = str(_get(d, "rule_clause") or _get(d, "rule_id") or "-")
            reason_txt = str(_get(d, "reason") or "")[:120]

            decl_table_rows.append([
                Paragraph(str(c_name), small),
                Paragraph(c_val, small),
                d_status,
                Paragraph(rule_ref, small),
                Paragraph(reason_txt, small),
            ])
            color = DECL_STATUS_COLORS.get(d_status, colors.black)
            decl_style_commands.append(("TEXTCOLOR", (2, row_idx), (2, row_idx), color))
            decl_style_commands.append(("FONTNAME", (2, row_idx), (2, row_idx), "Helvetica-Bold"))

        decl_table = Table(
            decl_table_rows,
            colWidths=[42 * mm, 34 * mm, 25 * mm, 28 * mm, 48 * mm],
            repeatRows=1,
        )
        decl_table.setStyle(TableStyle(decl_style_commands))
        story.append(decl_table)
        story.append(Spacer(1, 10))

    # --- Findings ----------------------------------------------------------
    # What this section SAYS is decided in `build_findings_section`, which is
    # pure and therefore testable; this block only draws it.
    section = build_findings_section(inspection)

    story.append(Paragraph(section["heading"], h2))

    if section["warning"]:
        story.append(Paragraph(section["warning"], disclaimer_style))
        story.append(Spacer(1, 6))

    rows = section["rows"]
    if rows:
        # Header cells are Paragraphs, not bare strings: a bare string cannot
        # wrap, so a header wider than its column silently overflows into the
        # next one and the printed table reads "Rule versionStatus". A report
        # whose column headers run together is not a document an inspector
        # should be asked to rely on.
        header_style = ParagraphStyle(
            "TableHeader", parent=small, fontName="Helvetica-Bold",
            textColor=colors.black, leading=9,
        )
        table_rows = [[
            Paragraph(text, header_style)
            for text in ("Rule / Field", "Rule version", "Status", "Reason",
                         "Evidence", "Conf.")
        ]]
        for row in rows:
            table_rows.append([
                Paragraph(row["label"], small),
                Paragraph(row["rule_version"], small),
                row["status"],
                Paragraph(row["reason"], small),
                Paragraph(row["evidence"], small),
                row["confidence"],
            ])

        findings_table = Table(
            table_rows,
            colWidths=[34 * mm, 16 * mm, 20 * mm, 49 * mm, 45 * mm, 13 * mm],
            repeatRows=1,
        )
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_index, row in enumerate(rows, start=1):
            color = STATUS_COLORS.get(row["status"], colors.black)
            style_commands.append(("TEXTCOLOR", (2, row_index), (2, row_index), color))
            style_commands.append(("FONTNAME", (2, row_index), (2, row_index), "Helvetica-Bold"))
        findings_table.setStyle(TableStyle(style_commands))
        story.append(findings_table)

    story.append(Spacer(1, 10))
    story.append(Paragraph(section["closing"], small))

    # --- Grounded Statutory Standards (RAG) --------------------------------
    grounded_list = rag_grounding or _get(inspection, "rag_grounding") or []
    if grounded_list:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Grounded Statutory Provisions & Standards (RAG Knowledge)", h2))
        story.append(Paragraph(
            "Statutory provisions grounded by retrieval against authoritative Legal Metrology and sectoral legal acts. "
            "Grounded knowledge determines applicable clauses and evidence thresholds; the deterministic Rule Engine evaluates compliance.",
            disclaimer_style,
        ))
        story.append(Spacer(1, 6))

        rag_header_style = ParagraphStyle(
            "RagTableHeader", parent=small, fontName="Helvetica-Bold",
            textColor=colors.black, leading=9,
        )
        rag_table_rows = [[
            Paragraph(t, rag_header_style)
            for t in ("Rule / Provision", "Framework", "Version & Date", "Applicability", "Statutory Source Citation")
        ]]
        for g in grounded_list:
            rid = _get(g, "rule_id", "-")
            mod = str(_get(g, "module", "-")).upper()
            ver = f"{_get(g, 'rule_version', '-')} ({_get(g, 'effective_date', '-')})"
            app = _get(g, "applicability", "APPLICABLE")
            src = _get(g, "source_reference", "-")
            rag_table_rows.append([
                Paragraph(str(rid), small),
                Paragraph(str(mod), small),
                Paragraph(str(ver), small),
                Paragraph(str(app), small),
                Paragraph(str(src), small),
            ])

        rag_table = Table(
            rag_table_rows,
            colWidths=[40 * mm, 20 * mm, 38 * mm, 24 * mm, 55 * mm],
            repeatRows=1,
        )
        rag_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f4f8")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(rag_table)

    doc.build(story)
    return buffer.getvalue()

