import { ArrowLeft, Download, FileCheck2 } from "lucide-react";
import { useState } from "react";

import { AppHeader } from "@/components/layout";
import { Button, ErrorBanner, StatusBadge } from "@/components/ui";
import { formatDate } from "@/lib/format";
import { reportPdfAvailable, reportPdfUrl } from "@/lib/api-client";
import type { Inspection } from "@/lib/types";

export function ReportView({ inspection, onBack }: { inspection: Inspection; onBack: () => void }) {
  const [pdfState, setPdfState] = useState<"idle" | "checking" | "available" | "unavailable">("idle");

  async function handleDownload() {
    setPdfState("checking");
    const available = await reportPdfAvailable(inspection.id);
    if (available) {
      window.open(reportPdfUrl(inspection.id), "_blank");
      setPdfState("available");
    } else {
      setPdfState("unavailable");
    }
  }

  return (
    <>
      <AppHeader title="Report preview" />
      <main className="mx-auto max-w-4xl space-y-5 px-4 pb-28 pt-6 sm:px-6 md:pb-10 lg:px-8 lg:pt-10">
        <div className="flex items-center justify-between">
          <button type="button" onClick={onBack} className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to result</button>
          <Button variant="secondary" onClick={() => void handleDownload()} disabled={pdfState === "checking"}>
            <Download className="h-4 w-4" />
            {pdfState === "checking" ? "Checking…" : pdfState === "available" ? "Opened" : "Download report"}
          </Button>
        </div>
        {pdfState === "unavailable" && (
          <ErrorBanner message="PDF generation isn't available on this backend yet — showing the on-screen preview only." />
        )}
        <article className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-10">
          <div className="flex flex-col justify-between gap-6 border-b border-border pb-7 sm:flex-row">
            <div>
              <div className="flex items-center gap-2 text-brand"><FileCheck2 className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-[.18em]">Legal metrology</span></div>
              <h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Inspection report</h2>
              <p className="mt-2 text-sm text-muted-foreground">Generated by THE INSPECTORS · SIH 2026</p>
            </div>
            <StatusBadge status={inspection.status} />
          </div>
          <div className="grid gap-5 border-b border-border py-7 sm:grid-cols-3">
            <div><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Product</p><p className="mt-2 text-sm font-semibold">{inspection.product}</p><p className="mt-1 text-xs text-muted-foreground">{inspection.manufacturer}</p></div>
            <div><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Inspection ID</p><p className="mt-2 text-sm font-semibold">#{inspection.id}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(inspection.timestamp)}</p></div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Final scores</p>
              <p className="mt-2 text-sm font-semibold">
                {inspection.scoreBreakdown
                  ? `Verified: ${inspection.scoreBreakdown.verifiedCount} of ${inspection.scoreBreakdown.applicableCount} applicable · Assessed: ${inspection.scoreBreakdown.judgeableCount} of ${inspection.scoreBreakdown.applicableCount}`
                  : `Verified: ${inspection.verifiedScore ?? inspection.score}% · Reviewed: ${inspection.reviewedScore ?? inspection.score}%`}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                {inspection.declarations.filter((item) => item.status === "VERIFIED" || item.status === "EXEMPT").length}/{inspection.declarations.length} verified
                {inspection.pdpAreaCm2 ? ` · PDP: ${inspection.pdpAreaCm2} cm²` : ""}
              </p>
            </div>
          </div>
          <div className="py-7">
            <h3 className="text-base font-semibold">Extracted declarations</h3>
            <div className="mt-4 divide-y divide-border">
              {inspection.declarations.map((item) => (
                <div key={item.field} className="flex items-center justify-between py-3 text-sm">
                  <div>
                    <span>{item.field}</span>
                    {item.ruleId && <span className="ml-2 text-[10px] font-semibold text-muted-foreground">{item.ruleId}</span>}
                  </div>
                  <span className={item.status === "VERIFIED" || item.status === "EXEMPT" ? "font-semibold text-success" : item.status === "MISSING" ? "font-semibold text-destructive" : "font-semibold text-warning"}>{item.value}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="rounded-xl bg-muted p-5">
            <p className="text-xs font-bold uppercase tracking-[.15em] text-muted-foreground">Reviewer recommendation</p>
            <p className="mt-2 text-sm leading-6">
              {inspection.status === "COMPLIANT" ? "Record may be added to the compliance register after officer confirmation." :
               inspection.status === "VIOLATION" ? "Issue a review notice for missing or incomplete declarations before verification." :
               inspection.status === "EXEMPT" ? "No further action required under these rules; confirm the exemption basis if challenged." :
               "Review the original evidence and request a clearer package image before deciding."}
            </p>
          </div>
          <p className="mt-6 text-xs leading-5 text-muted-foreground">{inspection.disclaimer}</p>
        </article>
      </main>
    </>
  );
}
