"""
Train YOLO for Legal Metrology Packaged Commodities Region Detection.

Uses Ultralytics YOLO to fine-tune on the Legal Metrology dataset
generated by `tools/prepare_yolo_dataset.py`.

Usage:
    python tools/train_yolo.py --epochs 25 --batch 8 --model yolov8n.pt
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_DIR = PROJECT_ROOT / "dataset"
DATA_YAML = DATASET_DIR / "yolo" / "data.yaml"
WEIGHTS_DIR = PROJECT_ROOT / "backend" / "weights"


def train(
    model_name: str = "yolov8n.pt",
    epochs: int = 25,
    imgsz: int = 640,
    batch_size: int = 8,
    device: str = "0",  # "0" for GPU, "cpu" for CPU
) -> Path:
    try:
        from ultralytics import YOLO
    except ImportError:
        print("Ultralytics is required: pip install ultralytics", file=sys.stderr)
        sys.exit(1)

    if not DATA_YAML.exists():
        print(f"data.yaml not found at {DATA_YAML}. Building dataset first...")
        from tools.prepare_yolo_dataset import build_yolo_dataset

        build_yolo_dataset()

    print(f"Loading base model: {model_name}")
    model = YOLO(model_name)

    WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    project_dir = PROJECT_ROOT / "runs" / "train"

    print(f"Starting YOLO training for {epochs} epochs on {device}...")
    results = model.train(
        data=str(DATA_YAML),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch_size,
        device=device,
        project=str(project_dir),
        name="legal_metrology_yolo",
        exist_ok=True,
        save=True,
    )

    # Save best weights to backend/weights/best.pt and export to ONNX
    best_weights = project_dir / "legal_metrology_yolo" / "weights" / "best.pt"
    target_weights = WEIGHTS_DIR / "best.pt"
    if best_weights.exists():
        import shutil
        shutil.copy2(best_weights, target_weights)
        print(f"Successfully exported best weights to: {target_weights}")

        try:
            best_model = YOLO(str(target_weights))
            onnx_path = best_model.export(format="onnx", imgsz=imgsz)
            target_onnx = WEIGHTS_DIR / "best.onnx"
            if Path(onnx_path).exists():
                shutil.copy2(onnx_path, target_onnx)
                print(f"Successfully exported ONNX model to: {target_onnx}")
        except Exception as export_err:
            print(f"ONNX export note: {export_err}")
    else:
        print(f"Training completed. Check results at: {project_dir}")

    return target_weights


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train YOLO on Legal Metrology declarations")
    parser.add_argument("--model", type=str, default="yolov8n.pt", help="Base model")
    parser.add_argument("--epochs", type=int, default=20, help="Epochs")
    parser.add_argument("--batch", type=int, default=8, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")
    parser.add_argument("--device", type=str, default="cpu", help="Device (0 or cpu)")
    args = parser.parse_args()

    train(
        model_name=args.model,
        epochs=args.epochs,
        batch_size=args.batch,
        imgsz=args.imgsz,
        device=args.device,
    )
