"""
PDF report generation for a completed inspection.

Design goals:
- The PDF is a rendering of already-computed, persisted facts/findings. It
  does not perform any new legal evaluation.
- A clear disclaimer is always printed, matching the platform's legal
  posture: automated screening / pre-inspection aid, not a final legal
  determination.
- No external HTML/browser dependency (WeasyPrint has heavy native deps that
  are awkward in constrained/offline build environments); reportlab is pure
  Python and reliable to install.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

DISCLAIMER = (
    "This report is generated by an automated screening / pre-inspection aid "
    "under the Legal Metrology (Packaged Commodities) Rules, 2011. It is NOT "
    "a final legal determination. Findings marked UNCERTAIN or REVIEW "
    "REQUIRED must be resolved by an authorized Legal Metrology inspector "
    "before any enforcement action is taken."
)

STATUS_COLORS = {
    "PASS": colors.HexColor("#1a7f37"),
    "FAIL": colors.HexColor("#cf222e"),
    "UNCERTAIN": colors.HexColor("#9a6700"),
    "EXEMPT": colors.HexColor("#6639ba"),
}


def _status_of(obj: Any) -> str:
    value = _get(obj, "status")
    if hasattr(value, "value"):
        value = value.value
    return str(value or "UNCERTAIN").upper()


def _get(obj: Any, key: str, default: Any = None) -> Any:
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def build_inspection_report_pdf(inspection: Dict[str, Any]) -> bytes:
    """
    Render one inspection (as returned by db.get_inspection_detail /
    ProductInspection.model_dump()) into a PDF report and return the raw
    bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=16, spaceAfter=4,
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceBefore=10, spaceAfter=4)
    normal = styles["Normal"]
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#7a0000"), borderColor=colors.HexColor("#7a0000"),
        borderWidth=0.5, borderPadding=6, backColor=colors.HexColor("#fff5f5"),
    )

    story: list[Any] = []

    inspection_id = _get(inspection, "inspection_id", "unknown")
    story.append(Paragraph("Legal Metrology Compliance Inspection Report", title_style))
    story.append(Paragraph(f"Inspection ID: {inspection_id}", normal))
    story.append(Spacer(1, 4))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    story.append(Spacer(1, 10))

    # --- Summary table ---------------------------------------------------
    overall_status = _get(inspection, "overall_status", "UNCERTAIN")
    if hasattr(overall_status, "value"):
        overall_status = overall_status.value

    summary_rows = [
        ["Field", "Value"],
        ["Product / Product ID", str(_get(inspection, "product_id", "-"))],
        ["Product category", str(_get(inspection, "product_category", "-"))],
        ["Sale type", str(_get(inspection, "sale_type", "-"))],
        [
            "Net quantity",
            f"{_get(inspection, 'net_quantity_value', _get(inspection, 'package_weight_or_volume', '-'))} "
            f"{_get(inspection, 'net_quantity_unit', _get(inspection, 'package_weight_unit', ''))}",
        ],
        ["MRP", str(_get(inspection, "mrp", "not observed"))],
        ["Overall status", str(overall_status).upper()],
        ["Review required", str(_get(inspection, "review_required", False))],
        [
            "Generated",
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        ],
    ]
    exempt_reason = _get(inspection, "exempt_reason")
    if exempt_reason:
        summary_rows.append(["Exemption reason", str(exempt_reason)])

    summary_table = Table(summary_rows, colWidths=[55 * mm, 110 * mm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # --- Findings ----------------------------------------------------------
    story.append(Paragraph("Rule Findings", h2))
    findings = _get(inspection, "findings", []) or []
    facts = _get(inspection, "facts", []) or []

    rows_source = findings if findings else facts
    if not rows_source:
        story.append(Paragraph("No rule findings were recorded for this inspection.", normal))
    else:
        table_rows = [["Rule / Field", "Status", "Reason", "Confidence"]]
        for item in rows_source:
            label = _get(item, "rule_id") or _get(item, "field") or "-"
            status = _status_of(item)
            reason = str(_get(item, "reason", "") or "")[:220]
            confidence = _get(item, "confidence", None)
            confidence_str = f"{float(confidence):.2f}" if confidence is not None else "-"
            table_rows.append([
                Paragraph(str(label), small),
                status,
                Paragraph(reason, small),
                confidence_str,
            ])

        findings_table = Table(
            table_rows, colWidths=[35 * mm, 22 * mm, 88 * mm, 20 * mm], repeatRows=1
        )
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_index, item in enumerate(rows_source, start=1):
            status = _status_of(item)
            color = STATUS_COLORS.get(status, colors.black)
            style_commands.append(("TEXTCOLOR", (1, row_index), (1, row_index), color))
            style_commands.append(("FONTNAME", (1, row_index), (1, row_index), "Helvetica-Bold"))
        findings_table.setStyle(TableStyle(style_commands))
        story.append(findings_table)

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "Every finding above is traceable to a versioned rule identifier, the "
        "underlying extracted evidence, and a confidence score. Findings with "
        "status UNCERTAIN reflect insufficient evidence, not a legal "
        "determination of non-compliance.",
        small,
    ))

    doc.build(story)
    return buffer.getvalue()


def build_multi_surface_inspection_report_pdf(data: Dict[str, Any]) -> bytes:
    """
    Generate an official, comprehensive Legal Metrology Inspection Report PDF
    from multi-surface package fusion or single-surface CV inspection results.
    Includes statutory metadata, findings breakdown, and embedded evidence photos.
    """
    import base64
    from reportlab.platypus import Image as RLImage, KeepTogether

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=15, leading=18, spaceAfter=2, textColor=colors.HexColor("#0f172a")
    )
    subtitle_style = ParagraphStyle(
        "SubTitle", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#475569"), spaceAfter=6
    )
    h2 = ParagraphStyle(
        "H2", parent=styles["Heading2"], fontSize=11, leading=14, spaceBefore=8, spaceAfter=4, textColor=colors.HexColor("#1e293b")
    )
    normal = ParagraphStyle("NormalText", parent=styles["Normal"], fontSize=8.5, leading=11, textColor=colors.HexColor("#334155"))
    small = ParagraphStyle("SmallText", parent=styles["Normal"], fontSize=7.5, leading=9.5, textColor=colors.HexColor("#64748b"))
    bold_small = ParagraphStyle("BoldSmall", parent=styles["Normal"], fontSize=8, leading=10, textColor=colors.HexColor("#0f172a"), fontName="Helvetica-Bold")

    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=7.5, leading=9.5,
        textColor=colors.HexColor("#7c2d12"), borderColor=colors.HexColor("#fed7aa"),
        borderWidth=0.5, borderPadding=5, backColor=colors.HexColor("#fff7ed"),
    )

    story = []

    # 1. Header
    story.append(Paragraph("LEGAL METROLOGY COMPLIANCE INSPECTION REPORT", title_style))
    story.append(Paragraph("Packaged Commodities Rules, 2011 • Department of Consumer Affairs, Government of India", subtitle_style))
    story.append(Spacer(1, 4))

    # 2. Status Banner Box
    is_compliant = data.get("fused_compliance_verdict") == "COMPLIANT" or data.get("compliance_verdict") == "COMPLIANT" or data.get("is_compliant") is True
    verdict_text = "COMPLIANT — ALL MANDATORY DECLARATIONS VERIFIED" if is_compliant else "STATUTORY VIOLATION — NON-COMPLIANCE DETECTED"
    banner_bg = colors.HexColor("#ecfdf5") if is_compliant else colors.HexColor("#fef2f2")
    banner_fg = colors.HexColor("#065f46") if is_compliant else colors.HexColor("#991b1b")
    banner_border = colors.HexColor("#a7f3d0") if is_compliant else colors.HexColor("#fecaca")

    banner_table = Table(
        [[
            Paragraph(f"<b>FINAL INSPECTION VERDICT: {verdict_text}</b>", ParagraphStyle("Banner", parent=normal, fontSize=10.5, leading=13, textColor=banner_fg, alignment=1))
        ]],
        colWidths=[182 * mm]
    )
    banner_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), banner_bg),
        ("BOX", (0, 0), (-1, -1), 1, banner_border),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 6))

    # 3. Product & Inspection Metadata Table
    decls = data.get("fused_declarations") or data.get("declarations") or {}
    total_surfaces = data.get("total_surfaces") or len(data.get("surfaces", [])) or 1
    coverage = data.get("evidence_coverage_percent", 100.0 if is_compliant else 60.0)

    meta_rows = [
        [
            Paragraph("<b>Product / Commodity Name</b>", small),
            Paragraph(str(decls.get("common_name") or "Packaged Commodity"), bold_small),
            Paragraph("<b>Inspection Mode</b>", small),
            Paragraph(f"Multi-Surface Fusion ({total_surfaces} Surfaces)" if total_surfaces > 1 else "Single Package Scan", normal),
        ],
        [
            Paragraph("<b>Inspection Date / Time</b>", small),
            Paragraph(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), normal),
            Paragraph("<b>Evidence Coverage</b>", small),
            Paragraph(f"<b>{coverage}%</b> of Mandatory Rules", normal),
        ],
        [
            Paragraph("<b>Barcode / EAN</b>", small),
            Paragraph(str(decls.get("barcode") or "Not Observed"), normal),
            Paragraph("<b>Batch / Lot No.</b>", small),
            Paragraph(str(decls.get("batch_no") or decls.get("details", {}).get("batch_no", {}).get("raw_text") or "-"), normal),
        ],
    ]
    meta_table = Table(meta_rows, colWidths=[42 * mm, 50 * mm, 40 * mm, 50 * mm])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # 4. Fused Declarations Summary Table
    story.append(Paragraph("1. Verified Legal Metrology Declarations (Fused Across Surfaces)", h2))

    decl_rows = [
        ["Statutory Field", "Extracted Value", "Statutory Rule", "Verification Status"],
        ["Maximum Retail Price (MRP)", str(decls.get("mrp") or "Not Observed"), "Rule 6(1)(e)", "PASS" if decls.get("mrp") else "FAIL"],
        ["Net Quantity", str(decls.get("net_quantity") or "Not Observed"), "Rule 6(1)(c)", "PASS" if decls.get("net_quantity") else "FAIL"],
        ["Date of Manufacture / Packing", str(decls.get("mfg_date") or "Not Observed"), "Rule 6(1)(d)", "PASS" if decls.get("mfg_date") else "FAIL"],
        ["Expiry / Use By Date", str(decls.get("expiry_date") or "Not Observed"), "Rule 6(1)(d)", "PASS" if decls.get("expiry_date") else "INFO"],
        ["Unit Sale Price (USP)", str(decls.get("unit_price") or "Not Observed"), "Rule 6(1)(da)", "PASS" if decls.get("unit_price") else "INFO"],
        ["Manufacturer / Packer", str(decls.get("manufacturer") or "Not Observed"), "Rule 6(1)(a)", "PASS" if decls.get("manufacturer") else "FAIL"],
        ["Consumer Care Contact", str(decls.get("consumer_care") or "Not Observed"), "Rule 6(1)(f)", "PASS" if decls.get("consumer_care") else "FAIL"],
    ]

    decl_table = Table(decl_rows, colWidths=[48 * mm, 64 * mm, 38 * mm, 32 * mm])
    decl_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for row_idx, r in enumerate(decl_rows[1:], start=1):
        st = r[3]
        st_color = colors.HexColor("#16a34a") if st == "PASS" else (colors.HexColor("#dc2626") if st == "FAIL" else colors.HexColor("#475569"))
        decl_style.append(("TEXTCOLOR", (3, row_idx), (3, row_idx), st_color))
        decl_style.append(("FONTNAME", (3, row_idx), (3, row_idx), "Helvetica-Bold"))
        if row_idx % 2 == 0:
            decl_style.append(("BACKGROUND", (0, row_idx), (-1, row_idx), colors.HexColor("#f8fafc")))

    decl_table.setStyle(TableStyle(decl_style))
    story.append(decl_table)
    story.append(Spacer(1, 8))

    # 5. Statutory Findings & Legal Assessment Table
    facts = data.get("fused_compliance_facts") or data.get("compliance_facts") or []
    if facts:
        story.append(Paragraph("2. Statutory Rule Compliance Findings (LMPC Rules, 2011)", h2))
        fact_rows = [["Rule Clause", "Target Field", "Status", "Observed Value", "Statutory Requirement"]]
        for f in facts:
            st = f.get("status", "UNCERTAIN")
            fact_rows.append([
                Paragraph(str(f.get("rule", "-")), small),
                Paragraph(str(f.get("field", "-")), bold_small),
                st,
                Paragraph(str(f.get("value") or "Missing"), small),
                Paragraph(str(f.get("description", "-")), small),
            ])

        fact_table = Table(fact_rows, colWidths=[28 * mm, 32 * mm, 20 * mm, 38 * mm, 64 * mm])
        fact_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 3.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_idx, f in enumerate(facts, start=1):
            st = f.get("status", "UNCERTAIN")
            st_color = colors.HexColor("#16a34a") if st == "PASS" else (colors.HexColor("#dc2626") if st == "FAIL" else colors.HexColor("#d97706"))
            fact_style.append(("TEXTCOLOR", (2, row_idx), (2, row_idx), st_color))
            fact_style.append(("FONTNAME", (2, row_idx), (2, row_idx), "Helvetica-Bold"))
            if row_idx % 2 == 0:
                fact_style.append(("BACKGROUND", (0, row_idx), (-1, row_idx), colors.HexColor("#f8fafc")))

        fact_table.setStyle(TableStyle(fact_style))
        story.append(fact_table)
        story.append(Spacer(1, 8))

    # 6. Embedded Visual Evidence (Annotated Surfaces)
    surfaces = data.get("surfaces", [])
    if not surfaces and data.get("overlay_base64"):
        surfaces = [{
            "image_name": data.get("image_name", "package.png"),
            "overlay_base64": data.get("overlay_base64"),
            "compliance_verdict": data.get("compliance_verdict", "INSPECTED")
        }]

    if surfaces:
        story.append(Paragraph("3. Photographic Evidence & Annotated Visual Inspection", h2))
        img_cells = []
        for s_idx, s in enumerate(surfaces):
            overlay_b64 = s.get("overlay_base64")
            if overlay_b64 and "base64," in overlay_b64:
                raw_b64 = overlay_b64.split("base64,")[1]
            else:
                raw_b64 = overlay_b64

            if raw_b64:
                try:
                    img_bytes = base64.b64decode(raw_b64)
                    img_io = io.BytesIO(img_bytes)
                    rl_img = RLImage(img_io, width=85 * mm, height=95 * mm)
                    v_badge = s.get("compliance_verdict", "INSPECTED")
                    cap = Paragraph(f"<b>Surface {s_idx + 1}: {s.get('image_name', 'package')}</b> ({v_badge})", small)
                    img_cells.append([rl_img, cap])
                except Exception:
                    pass

        if img_cells:
            table_grid = []
            for i in range(0, len(img_cells), 2):
                row_imgs = []
                row_caps = []
                for j in range(i, min(i + 2, len(img_cells))):
                    row_imgs.append(img_cells[j][0])
                    row_caps.append(img_cells[j][1])
                while len(row_imgs) < 2:
                    row_imgs.append("")
                    row_caps.append("")
                table_grid.append(row_imgs)
                table_grid.append(row_caps)

            img_table = Table(table_grid, colWidths=[91 * mm, 91 * mm])
            img_table.setStyle(TableStyle([
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(KeepTogether(img_table))
            story.append(Spacer(1, 8))

    # 7. Disclaimer & Inspector Sign-off Box
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<b>STATUTORY DISCLAIMER:</b> This inspection report is generated by an automated Legal Metrology computer vision screening system. Findings marked VIOLATION or UNCERTAIN should be verified by an authorized Legal Metrology Officer under the Legal Metrology Act, 2009 before formal enforcement action.",
        disclaimer_style
    ))
    story.append(Spacer(1, 6))

    signoff_table = Table(
        [
            [
                Paragraph("<b>Inspected By:</b> AI Vision Engine (LMPC v2.4)", small),
                Paragraph("<b>Verified By (Officer Signature):</b> ___________________", small),
                Paragraph("<b>Date:</b> ______________", small),
            ]
        ],
        colWidths=[60 * mm, 80 * mm, 42 * mm]
    )
    signoff_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(signoff_table)

    doc.build(story)
    return buffer.getvalue()
